export const Theatre_OWNER_LOGIN_REQUEST = 'THEATRE_OWNER_LOGIN_REQUEST';
export const Theatre_OWNER_LOGIN_SUCCESS = 'THEATRE_OWNER_LOGIN_SUCCESS';
export const Theatre_OWNER_LOGIN_FAIL = 'THEATRE_OWNER_LOGIN_FAIL';

export const Theatre_OWNER_REGISTER_REQUEST = 'THEATRE_OWNER_REGISTER_REQUEST';
export const Theatre_OWNER_REGISTER_SUCCESS = 'THEATRE_OWNER_REGISTER_SUCCESS';
export const Theatre_OWNER_REGISTER_FAIL = 'THEATRE_OWNER_REGISTER_FAIL';

export const Theatre_OWNER_LOGOUT = 'THEATRE_OWNER_LOGOUT';

