export const SCREENS_FETCH_START = 'SCREENS_FETCH_START';
export const SCREENS_FETCH_SUCCESS = 'SCREENS_FETCH_SUCCESS';
export const SCREENS_FETCH_ERROR = 'SCREENS_FETCH_ERROR';

export const SCREEN_CREATE_START = 'SCREEN_CREATE_START';
export const SCREEN_CREATE_SUCCESS = 'SCREEN_CREATE_SUCCESS';
export const SCREEN_CREATE_ERROR = 'SCREEN_CREATE_ERROR';

export const SCREEN_UPDATE_START = 'SCREEN_UPDATE_START';
export const SCREEN_UPDATE_SUCCESS = 'SCREEN_UPDATE_SUCCESS';
export const SCREEN_UPDATE_ERROR = 'SCREEN_UPDATE_ERROR';

export const SCREEN_DELETE_START = 'SCREEN_DELETE_START';
export const SCREEN_DELETE_SUCCESS = 'SCREEN_DELETE_SUCCESS';
export const SCREEN_DELETE_ERROR = 'SCREEN_DELETE_ERROR';

export const SCREEN_FORM_RESET = 'SCREEN_FORM_RESET';
export const CLEAR_SCREEN_ERROR = 'CLEAR_SCREEN_ERROR';
export const SET_SELECTED_SCREEN = 'SET_SELECTED_SCREEN';
export const TOGGLE_FORM_MODAL = 'TOGGLE_FORM_MODAL';
